export const CLEAR_REDUCER = 'CLEAR_REDUCER_COMIC_DETAILS';
export const LOADING = 'LOADING_COMIC_DETAILS';
export const ADD_COMIC = 'ADD_COMIC';
export const SAGA_COMIC_DETAILS = 'SAGA_COMIC_DETAILS';
export const SAGA_BUY_COMIC = 'SAGA_BUY_COMIC';
